### ISSUE TITLE
Grammer mistake in 1.2 About this book - "Motes"

### ISSUE THREAD

**Issue by santoshborate** [kapilsharma/AngularQuickNotes#1]
Now a days,he is making his **motes** in markdown.

Correct to "Now a days,he is making his **notes** in markdown."

Few more 
1. This JavaScript object contains **few few** important properties (Page no 16)
2. **as good a good** coding practice (Page no 18)

**Comment by kapilsharma** [comment]
Thanks @santoshborate 
It is fixed, will be available with next patch version along with few other typo and grammar fixes. I'll close the issue once next version of book (v0.1.1) is available.

**Comment by kapilsharma** [comment]
All these issues are closed with version 0.1.1 and fixes available in latest PDF.
Closing issue.
